#! /bin/bash
echo "$(pwd)/alitext.py" > ~/.alitext_locale
echo "example.atxt" > .tmp_atxt
echo "Setup running..."
python3 alitext.py
sleep 2s
echo "Read the README for more information"
sleep 3s
echo "Restarting bash..."
bash
